### ISSUE TITLE
Make the source feed locally available

### ISSUE THREAD

**Issue by 5310** [onnyyonn/feed#6]
So that it's available at https://onnyyonn.github.io/feed/feed.atom to subscribe, with some amount of control on the content. ~~Also so that pushing content to it automatically updates the site.~~

**Comment by onnyyonn** [comment]
Fixed by commit ba11ebde8cc59ca31b0c12a005fcee24eef900a8 and 84cbb6a98c0c09d4bef12694cc5144e3a0601627

**Comment by 5310** [comment]
I can continue to sub to the remote feed, right?

**Comment by onnyyonn** [comment]
> I can continue to sub to the remote feed, right?

@5310 You can. But I may think about adding multiple source feeds in future. Don't know how that'll work though.

**Comment by 5310** [comment]
What will these other sources be, btw?

**Comment by onnyyonn** [comment]
The main reason I am thinking about multiple sources is that there is possibility of me loosing the current source feed. Because this is from a selfhosted TTRSS instance. If someday a migration goes wrong, I may end up having a new source. In that case I can build the site from multiple feeds so that the  site doesn't loose any data.

But there are some other additional sources I am considering as well. What if there is a feed of my retweets that gets added to the site? Or my Github stars? I am also considering creating a feed for my _TIL_. But that may get its own site.

**Comment by 5310** [comment]
Ah, they're all personal sources. That's all I wanted to know :+1:

**Comment by 5310** [comment]
> What if there is a feed of my retweets that gets added to the site? Or my Github stars? I am also considering creating a feed for my _TIL_.

That's also what I wanted to do, what with Mastodon being the default "freeform content" source. But I am getting distracted by Knottery again... :point_right::point_left:
